version: "3.5"
services:
    broker: 
        # image: eclipse-mosquitto:1.6
        # ports:
        #   - 1883:1883
        # volumes:
        # - type: bind
        #   source: ./mosquitto.conf
        #   target: /mosquitto/config/mosquitto.conf
        #   read_only: true
        image: tt:latest
        ports:
          - 1883:1883
        command: /tt serve -b :1883

    ttsub:
        image: tt:latest
        command: /tt sub -s broker:1883
        depends_on:
          - broker
