version: "3.5"
services:
    broker: 
        image: eclipse-mosquitto:1.6
        ports:
          - 1883:1883
        volumes:
        - type: bind
          source: ./mosquitto.conf
          target: /mosquitto/config/mosquitto.conf
          read_only: true

    ttserve:
        image: tt:latest
        container_name: ttserve
        ports:
          - 1882:1882
        command: /tt serve -b :1882

    ttsub:
        image: tt:latest
        container_name: ttsub-broker
        command: /tt sub -s broker:1883
        depends_on:
          - broker

    ttsubserv:
        image: tt:latest
        container_name: ttsub-serve
        command: /tt sub -s ttserve:1882
        depends_on:
          - ttserve
          
