// Code generated by "stringer -type ReasonCode"; DO NOT EDIT.

package mq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[UnspecifiedError-128]
	_ = x[MalformedPacket-129]
	_ = x[ProtocolError-130]
	_ = x[ImplementationSpecificError-131]
	_ = x[UnsupportedProtocolVersion-132]
	_ = x[ClientIdentifierNotValid-133]
	_ = x[BadUserNameOrPassword-134]
	_ = x[NotAuthorized-135]
	_ = x[ServerUnavailable-136]
	_ = x[ServerBusy-137]
	_ = x[Banned-138]
	_ = x[BadAuthenticationMethod-140]
	_ = x[TopicNameInvalid-144]
	_ = x[ReceiveMaximumExceeded-147]
	_ = x[PacketTooLarge-149]
	_ = x[QuotaExceeded-151]
	_ = x[PayloadFormatInvalid-153]
	_ = x[RetainNotSupported-154]
	_ = x[QoSNotSupported-155]
	_ = x[UseAnotherServer-156]
	_ = x[ServerMoved-157]
	_ = x[SharedSubscriptionsNotSupported-158]
	_ = x[ConnectionRateExceeded-159]
	_ = x[SubscriptionIdentifiersNotSupported-161]
	_ = x[WildcardSubscriptionsNotSupported-162]
}

const (
	_ReasonCode_name_0 = "Success"
	_ReasonCode_name_1 = "UnspecifiedErrorMalformedPacketProtocolErrorImplementationSpecificErrorUnsupportedProtocolVersionClientIdentifierNotValidBadUserNameOrPasswordNotAuthorizedServerUnavailableServerBusyBanned"
	_ReasonCode_name_2 = "BadAuthenticationMethod"
	_ReasonCode_name_3 = "TopicNameInvalid"
	_ReasonCode_name_4 = "ReceiveMaximumExceeded"
	_ReasonCode_name_5 = "PacketTooLarge"
	_ReasonCode_name_6 = "QuotaExceeded"
	_ReasonCode_name_7 = "PayloadFormatInvalidRetainNotSupportedQoSNotSupportedUseAnotherServerServerMovedSharedSubscriptionsNotSupportedConnectionRateExceeded"
	_ReasonCode_name_8 = "SubscriptionIdentifiersNotSupportedWildcardSubscriptionsNotSupported"
)

var (
	_ReasonCode_index_1 = [...]uint8{0, 16, 31, 44, 71, 97, 121, 142, 155, 172, 182, 188}
	_ReasonCode_index_7 = [...]uint8{0, 20, 38, 53, 69, 80, 111, 133}
	_ReasonCode_index_8 = [...]uint8{0, 35, 68}
)

func (i ReasonCode) String() string {
	switch {
	case i == 0:
		return _ReasonCode_name_0
	case 128 <= i && i <= 138:
		i -= 128
		return _ReasonCode_name_1[_ReasonCode_index_1[i]:_ReasonCode_index_1[i+1]]
	case i == 140:
		return _ReasonCode_name_2
	case i == 144:
		return _ReasonCode_name_3
	case i == 147:
		return _ReasonCode_name_4
	case i == 149:
		return _ReasonCode_name_5
	case i == 151:
		return _ReasonCode_name_6
	case 153 <= i && i <= 159:
		i -= 153
		return _ReasonCode_name_7[_ReasonCode_index_7[i]:_ReasonCode_index_7[i+1]]
	case 161 <= i && i <= 162:
		i -= 161
		return _ReasonCode_name_8[_ReasonCode_index_8[i]:_ReasonCode_index_8[i+1]]
	default:
		return "ReasonCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
